### ISSUE TITLE
Fails to run with latest android SDK

### ISSUE THREAD

**Issue by michaelbln** [Wizcorp/cordova-plugin-wizviewmanager#62]
When built with android-sdk 19, the webview creation fails with some null pointer exceptions. Luckily, if you built it with older sdk, it's running successfully running on android 4.4.

**Comment by alexandervlpl** [comment]
Got the plugin working with Android 22 and Cordova 5.1.1 (at least the plugin config and webView). Made a pull request to the develop branch.

**Comment by jrouault** [comment]
Tested and working on Cordova 6.4.0 and Android 6.0.1. Please re-open the issue if you still have it after updating.
