### ISSUE TITLE
html alert is not working within the webview

### ISSUE THREAD

**Issue by greaterking** [Wizcorp/cordova-plugin-wizviewmanager#68]
it seems like alert or confirm dialogues don't work in the created webviews. Also I get this error in all webviews that gets created.

Uncaught SyntaxError: Unexpected end of input 

and this js below seems like the alert is trying to be displayed but something is not working right

<script>(function() {with (this[2]) {with (this[1]) {with (this[0]) {return function(event) {return confirm('Are you sure you want to delete this message?\nThis action can not be undone');
};}}}})</script>

please help. I'm using version 1.2.0 of the plugin. thanks.

**Comment by jayalak** [comment]
Hi, i have a problem in displaying customized window.alert over inappbrowser. Can some help me out soon on this????
