### ISSUE TITLE
Can't postMessage to view

### ISSUE THREAD

**Issue by pbl** [Wizcorp/cordova-plugin-wizviewmanager#77]
Hi,

Have been sitting for quite some time now trying to get to wizViewMessenger.postMessage(Data message, String targetView); function to work. Creating the view and showing goes fine. But when I post at message nothing happens. The view never gets the message and their is no error message from the cordova application either.  

The other way around works perfectly i.e. sending a message from the view to the cordova application. 

This is the code in the cordova application:

wizViewManager.create("pollux", {
      src: "http://pollux-server.herokuapp.com/",
 }, success, fail);

function success(){
    wizViewManager.show("pollux");
    wizViewMessenger.postMessage("Message from phoneGap", "pollux");
    console.log("success");
}

This is the code in the webapplication:

$( document ).ready(function() {
    window.addEventListener('message', wizMessageReceiver, false);
});

function wizMessageReceiver (event) {
        console.log("Message received from PhoneGap: " + event);
    $("#phonegap-msg").text(event.data);
}

**Comment by jrouault** [comment]
Closing as this should have been fixed with #90. Please re-open the issue if you still have it after updating.
