### ISSUE TITLE
Need help with android installation

### ISSUE THREAD

**Issue by hamadrehman** [Wizcorp/cordova-plugin-wizviewmanager#91]
Hi, Can you please provide a step by step guide for using this plugin on android? I've searched for hours but in vain. Any guidance is appreciated.

**Comment by aogilvie** [comment]
It's in the README, if you have still have issues with the add plugin command please re-open this issue. Thanks. https://github.com/Wizcorp/cordova-plugin-wizviewmanager/blob/master/README.md

**Comment by ronkorving** [comment]
Closing this on suggestion by @aogilvie.
@hamadrehman, If you still have any questions, please be very precise in what you would like to know and maybe we can help you out :)
